### PR TITLE
It's the final pull request.

### PR DESCRIPTION
**Pull request by kvnbanunu**
This is it.
Alright guys.
It's been amazing.

### CODE REVIEW

**Review by Catherine-Queenan — APPROVED** [review]
It has been an honor soldiers.

**Comment by filipbudd** [comment]
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA (hopefully this was constructive)

**Comment by EugenieVK** [comment]
This is the end

**Comment by evin-gg** [comment]
There are many web apps out there, but they all share the same sky. One sky, one destiny.

**Pull request merged**
